name: Build Windows App

on:
  # 允许在 GitHub 网页上手动点击按钮触发打包
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest  # 告诉 GitHub 给我用一台 Windows 电脑
    steps:
      - name: 下载代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装 Rust
        uses: dtolnay/rust-toolchain@stable

      - name: 安装 pnpm
        run: npm install -g pnpm

      - name: 安装前端依赖
        run: pnpm install

      - name: 开始打包 Tauri 应用
        env:
            TAURI_SIGNING_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5WXBBRVRvbDF4QXQ0OU43QWNVeGtSb09PamlqbnJhQUtodzJ3dlJteHFrb0FBQkFBQUFBQUFBQUFBQUlBQUFBQXJ5UEZua0I5d0x2Qk9zTEJtM1hzNUZvcDFydGN5QWliTVBQQVJFT2FoOXVNWW5odXdPbDdVc3AwQWNwYjhINXh2RkJ1V2FzcnVPQ1pET3NwL1p5SHkzWkJQbWJrcmw0MUYyVDZjb1lnc1lLc1haODZ0MjZiT0JwRmxJVzMyZUhwdnlOS2g4Nm0yUzA9Cg==%
        run: pnpm tauri build

      - name: 上传打包好的 exe 安装包
        uses: actions/upload-artifact@v4
        with:
          name: EcoPaste-Windows-Installer
          path: src-tauri/target/release/bundle/nsis/*.exe
